keys:
  - &personal_age_key age18c0x420uaz9dmk7glcj4kwv7f0ndm9puf5awuvw3est9sfdxpfasgdvy4x

creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
        - *personal_age_key
