vim.g.mapleader = ' '

vim.opt.colorcolumn = "80"
vim.opt.termguicolors = true
vim.opt.ignorecase = true
vim.opt.swapfile = false
vim.opt.autoindent = true
vim.opt.expandtab = true
vim.opt.tabstop = 2
vim.opt.softtabstop = 2
vim.opt.shiftwidth = 2
vim.opt.shiftround = true
vim.opt.list = true
vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.numberwidth = 2
vim.opt.wrap = false
vim.opt.cursorline = true
vim.opt.scrolloff = 8
vim.opt.inccommand = "nosplit"
vim.opt.undofile = true
vim.opt.completeopt = {"menuone", "popup", "noinsert"}
vim.opt.hlsearch = false
